const data = [
  {name: 'Laptop', group: 'Electroincs', value: 1},
  {name: 'Pen', group: 'Utils', value: 2},
  {name: 'Apple', group: 'Fruits', value: 3},
  {name: 'Pencil', group: 'Utils', value: 4},
  {name: 'Table', group: 'Furniture', value: 5},
  {name: 'Phone', group: 'Electroincs', value: 6},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
  {name: 'Grapes', group: 'Fruits', value: 7},
  {name: 'School', group: 'Buildings', value: 8},
  {name: 'Watermelon', group: 'Fruits', value: 9},
  {name: 'Ear Phone', group: 'Electroincs', value: 10},
  {name: 'Rubber', group: 'Utils', value: 11},
];
export default data;
